### ISSUE TITLE
Faltou fazer das rotas v6

### ISSUE THREAD

**Issue by andrebolzan** [andrediashexa/twitter-block#1]
bgpq4 -6 -m 32 -l prefix_list_$asn AS$asn > tmp_prefixes.txt

**Comment by andrediashexa** [comment]
Bem pontuado. Vou adicionar no script para também fazer para v6.

**Comment by bernardesarthur** [comment]
Vou trabalhar nisso nas próximas semanas.

**Comment by andrediashexa** [comment]
Já está sendo feito, todavia tem um bug ainda:

Rotas estáticas IPv6 geradas em static_routes_ipv6.txt
ipv6 route-static ! generated prefix-list prefix_list_63179 is empty NULL0
ipv6 route-static ipv6 prefix-list prefix_list_63179 deny ::/0 NULL0
ipv6 route-static ! generated prefix-list prefix_list_54888 is empty NULL0
ipv6 route-static ipv6 prefix-list prefix_list_54888 deny ::/0 NULL0
ipv6 route-static ! generated prefix-list prefix_list_35995 is empty NULL0
ipv6 route-static ipv6 prefix-list prefix_list_35995 deny ::/0 NULL0
ipv6 route-static  2400:6680::/32 NULL0
ipv6 route-static  2400:6680:f000::/36 NULL0
ipv6 route-static  2606:1f80::/32 NULL0
ipv6 route-static  2606:1f80:f000::/36 NULL0
ipv6 route-static  2a04:9d40::/29 NULL0
ipv6 route-static  2a04:9d40:f000::/36 NULL0
Deseja gerar os comandos de remoção para o fabricante selecionado? (s/n):

**Comment by andrediashexa** [comment]
ipv6 corrigido :D
